- name: Evaluate User Workload Monitoring
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: absent
    kind: ConfigMap
    api_version: v1
    definition:
      metadata:
        name: cluster-monitoring-config
        namespace: openshift-monitoring

- name: Delete {{ grafana_project }} Namespace
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: absent
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ grafana_project }}"
