{
 "title": "Camel - Quarkus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(application_camel_route_count{namespace=\"demo-camel-k\"}, job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(application_camel_route_count{job=\"$job\"}, pod)"
    }
   },
   {
    "name": "routeId",
    "label": "RouteId",
    "query": {
     "query": "label_values(application_camel_route_exchanges_failed_total{job=\"$job\"}, routeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Endpoint Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "processing_seconds_count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_exchange_processing_seconds_count{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "{{ endpointName }}"
    }
   ]
  },
  {
   "title": "processing_rate_per_second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_camel_exchange_processing_rate_per_second{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "{{ endpointName }}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{job=\"$job\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "base_gc_time_total_seconds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_gc_time_total_seconds{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "vendor_memoryPool_usage_max_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_max_bytes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "vendor_memory_maxNonHeap_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_maxNonHeap_bytes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "base_thread_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "base_memory_usedHeap_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "$pod"
    }
   ]
  },
  { "title": "Camel Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "route_exchanges_completed_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_completed_total{ job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  },
  {
   "title": "route_exchanges_failed_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_exchanges_failed_total{job=\"$job\", pod=\"$pod\", routeId=\"$routeId\"}"
    }
   ]
  }
 ]
}