- hosts: localhost
  name: Install Camel K Demo
  vars:
    delete_demo: false
    verify_tls: false
    demo_project: demo-camel-k
    demo_display_name: Demo Camel K
    demo_description: Project used in Camel K demo
    grafana_project: '{{ demo_project }}-grafana'
    grafana_user: root
    grafana_password: secret
    enable_logging: true
    enable_user_workload_monitoring: true
  tasks:

    - name: 'Check Parameters'
      ansible.builtin.fail: msg="This play requires 'server' and 'token' to be defined"
      when:
        - server is not defined
        - token is not defined

    - name: 'Define domain'
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: 'Evaluate {{ demo_project }} Namespace'
      when: not delete_demo
      k8s:
        api_key: '{{ token }}'
        host: '{{ server }}'
        validate_certs: '{{ verify_tls }}'
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ demo_project }}"
            annotations:
              openshift.io/description: "{{ demo_description }}"
              openshift.io/display-name: "{{ demo_display_name }}"

    - name: Evaluate Operator Group
      when: not delete_demo
      k8s:
        api_key: '{{ token }}'
        host: '{{ server }}'
        validate_certs: '{{ verify_tls }}'
        state: present
        api_version: operators.coreos.com/v1
        kind: OperatorGroup
        definition:
          metadata:
            name: '{{ demo_project }}-operatorgroup'
            namespace: '{{ demo_project }}'
          spec:
            targetNamespaces:
              - '{{ demo_project }}'

    - name: Include Logging role
      ansible.builtin.include_role:
        name: logging

    - name: Include Monitoring role
      ansible.builtin.include_role:
        name: monitoring

    - name: Include Camel K role
      ansible.builtin.include_role:
        name: camel-k

    - name: Delete {{ demo_project }} Namespace
      when: delete_demo | bool
      k8s:
        api_key: '{{ token }}'
        host: '{{ server }}'
        validate_certs: '{{ verify_tls }}'
        state: absent
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ demo_project }}"
            annotations:
              openshift.io/description: "{{ demo_description }}"
              openshift.io/display-name: "{{ demo_display_name }}"
